apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: marianofsl/blogapp-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

    - image: marianofsl/blogapp-posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .

    - image: marianofsl/blogapp-comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .

    - image: marianofsl/blogapp-query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .

    - image: marianofsl/blogapp-moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .

    - image: marianofsl/blogapp-eventbus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.ts'
            dest: .